### PR TITLE
Add hero to case

### PR DESCRIPTION
**Pull request by CyrilleKolle**
link to fixa ticket: https://fixa.itiden.se/project/1362/tickets/100
link to fixa ticket:https://fixa.itiden.se/project/1362/tickets/99

### CODE REVIEW

**Review by ricllrstn — CHANGES_REQUESTED** [review]
Some things:
– [All] Size on hero-text on desktop breakpoints have changed, is now smaller than desired
– [Hem] 100 vh för Hem doesn't seem to work correctly
– [All] Titel (Välkommen etc) wrong size or/and class
– [Hem/All] Space missing between text and arrow (h1 used to have 12px margin-bottom which seem to be missing)
– [Case] Titel missing

**Review by ricllrstn — CHANGES_REQUESTED** [review]
– Space above and below arrow 24px
– Space title to top 160px for Kontakt and Case
– Titel sizo and/or class (should be 13/137.5)
– Add highlight animation for hero-text on Case

**Review by ricllrstn — CHANGES_REQUESTED** [review]
Nice work, some small things:
– Hero has no space above text at 640–767px and extra space between text and tags. At 768px the space at the top is back but still has extra space between text and tags.
– 100vh for Hem doesnt seem to work properly
– Class and/or text size for Titel is not correct, should be 13/137.5

**Review by ricllrstn — CHANGES_REQUESTED** [review]
Almost :)
Now Hem seem to work as intended but unfortunately case and kontakt doesn't. Now they also share to 100vh setting.

**Review by ricllrstn — APPROVED** [review]
Great stuff, I will approve now but please add the letter "t" to the word "enkel" on the kontakt page.

**Review by andreasbergqvist — APPROVED** [review]

**Pull request merged**
